# FA Notify configuration file

# Run a pprof debug server on http://localhost:6680/debug/pprof/
debug = true
logLevel = "DEBUG"
# For colors in log output, useful in IDEs that properly interpret them but don't show up as TTYs
logForceColors = true
# Output logs in JSON format instead. Overrides logForceColors.
logJSON = false
# The maximum number of FA users a single bot user is allowed to monitor for submissions and journals.
perUserMaxUserMonitors = 10
# The maximum number of FA users that all bot users are allowed to monitor, combined.
# Multiple bot users that monitor the same FA user do not count double.
globalMaxUserMonitors = 1000
# The maximum number of searches each bot user is allowed to monitor.
perUserMaxSearches = 10
# The maximum number of searches that all bot users are allowed to monitor, combined.
# Multiple bot users that monitor the exact same search do not count double.
globalMaxSearches = 1000

[tg]
# Get this token from @BotFather when you create your bot.
token = ""
# User ID of the owner (*not* the username). They will receive a message for
# every "error" level log message.
# You can use @userinfobot to get your user ID.
ownerID = 0
# Set TG client to debug mode, which logs a lot.
debug = false

[fa]
# How often to poll for searches/submissions. You can use common
# suffixes; see https://golang.org/pkg/time/#ParseDuration
pollInterval = "1m"
# Proxy server to use for FA requests. You can do something like
# ssh -D 18080 my-awesome-server.com
# to run a SOCKS5 proxy over an ssh connection, and then specify something like
# socks5://127.0.0.1:18080
# for this to use that proxy.
proxy = ""
# You probably want to set this to what your browser says it is.
userAgent = "fanotify/faapi/go"
# Requests to FA will not occur more frequently than this.
# Note: Requests of facdn (for downloading images) are not constrained by this.
rateLimit = "10s"
# The maximum amount of time for a single request to FA, including any retries.
# This should be at least as long as requestTimeout times retryLimit.
timeout = "1m"
# The maximum amount of time for a single request attempt to FA.
requestTimeout = "15s"
# The delay between retries for a single request.
retryDelay = "5s"
# How many times to retry a single request, whether it timed out or got an error
# code back from FA or Cloudflare.
retryLimit = 3

# Cookies to set on requests to FA. If you don't provide valid cookies that will
# get you logged in to an account, only general-rated artwork will be returned.
[[fa.cookies]]
name = "a"
value = "A"

[[fa.cookies]]
name = "b"
value = "B"

